/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asantos3
 */
public class Teclado extends javax.swing.JFrame {

    /**
     * Creates new form Teclado
     */
    public Teclado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_input = new javax.swing.JTextField();
        lbl_mostrador = new javax.swing.JLabel();
        btn_tecla_q = new javax.swing.JButton();
        btn_tecla_w = new javax.swing.JButton();
        btn_tecla_e = new javax.swing.JButton();
        btn_tecla_r = new javax.swing.JButton();
        btn_tecla_t = new javax.swing.JButton();
        btn_tecla_y = new javax.swing.JButton();
        btn_tecla_u = new javax.swing.JButton();
        btn_tecla_i = new javax.swing.JButton();
        btn_tecla_o = new javax.swing.JButton();
        btn_tecla_p = new javax.swing.JButton();
        btn_tecla_g = new javax.swing.JButton();
        btn_tecla_h = new javax.swing.JButton();
        btn_tecla_j = new javax.swing.JButton();
        btn_tecla_k = new javax.swing.JButton();
        btn_tecla_l = new javax.swing.JButton();
        btn_tecla_a = new javax.swing.JButton();
        btn_tecla_s = new javax.swing.JButton();
        btn_tecla_d = new javax.swing.JButton();
        btn_tecla_f = new javax.swing.JButton();
        btn_tecla_z = new javax.swing.JButton();
        btn_tecla_x = new javax.swing.JButton();
        btn_tecla_c = new javax.swing.JButton();
        btn_tecla_v = new javax.swing.JButton();
        btn_tecla_b = new javax.swing.JButton();
        btn_tecla_n = new javax.swing.JButton();
        btn_tecla_m = new javax.swing.JButton();
        btn_tecla_espaco = new javax.swing.JButton();
        lbl_smile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_input.setText("jTextField1");

        lbl_mostrador.setText("jLabel1");

        btn_tecla_q.setText("q");
        btn_tecla_q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_qActionPerformed(evt);
            }
        });

        btn_tecla_w.setText("w");
        btn_tecla_w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_wActionPerformed(evt);
            }
        });

        btn_tecla_e.setText("e");
        btn_tecla_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_eActionPerformed(evt);
            }
        });

        btn_tecla_r.setText("r");
        btn_tecla_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_rActionPerformed(evt);
            }
        });

        btn_tecla_t.setText("t");
        btn_tecla_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_tActionPerformed(evt);
            }
        });

        btn_tecla_y.setText("y");
        btn_tecla_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_yActionPerformed(evt);
            }
        });

        btn_tecla_u.setText("u");
        btn_tecla_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_uActionPerformed(evt);
            }
        });

        btn_tecla_i.setText("i");
        btn_tecla_i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_iActionPerformed(evt);
            }
        });

        btn_tecla_o.setText("o");
        btn_tecla_o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_oActionPerformed(evt);
            }
        });

        btn_tecla_p.setText("p");
        btn_tecla_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_pActionPerformed(evt);
            }
        });

        btn_tecla_g.setText("g");
        btn_tecla_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_gActionPerformed(evt);
            }
        });

        btn_tecla_h.setText("h");
        btn_tecla_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_hActionPerformed(evt);
            }
        });

        btn_tecla_j.setText("j");
        btn_tecla_j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_jActionPerformed(evt);
            }
        });

        btn_tecla_k.setText("k");
        btn_tecla_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_kActionPerformed(evt);
            }
        });

        btn_tecla_l.setText("l");
        btn_tecla_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_lActionPerformed(evt);
            }
        });

        btn_tecla_a.setText("a");
        btn_tecla_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_aActionPerformed(evt);
            }
        });

        btn_tecla_s.setText("s");
        btn_tecla_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_sActionPerformed(evt);
            }
        });

        btn_tecla_d.setText("d");
        btn_tecla_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_dActionPerformed(evt);
            }
        });

        btn_tecla_f.setText("f");
        btn_tecla_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_fActionPerformed(evt);
            }
        });

        btn_tecla_z.setText("z");
        btn_tecla_z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_zActionPerformed(evt);
            }
        });

        btn_tecla_x.setText("x");
        btn_tecla_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_xActionPerformed(evt);
            }
        });

        btn_tecla_c.setText("c");
        btn_tecla_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_cActionPerformed(evt);
            }
        });

        btn_tecla_v.setText("v");
        btn_tecla_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_vActionPerformed(evt);
            }
        });

        btn_tecla_b.setText("b");
        btn_tecla_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_bActionPerformed(evt);
            }
        });

        btn_tecla_n.setText("n");
        btn_tecla_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_nActionPerformed(evt);
            }
        });

        btn_tecla_m.setText("m");
        btn_tecla_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecla_mActionPerformed(evt);
            }
        });

        btn_tecla_espaco.setText("espaço");

        lbl_smile.setText(":)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_mostrador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_input, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_tecla_z)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tecla_x)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tecla_c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tecla_v)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tecla_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tecla_n)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tecla_m)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_tecla_espaco, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_tecla_q)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_w)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_e)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_r)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_t)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_y)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_u)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_i)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_o))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_tecla_a)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_s)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_d)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_f)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_g)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_h)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_j)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_k)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tecla_l)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lbl_smile))
                                    .addComponent(btn_tecla_p))))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_mostrador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tecla_q)
                    .addComponent(btn_tecla_w)
                    .addComponent(btn_tecla_e)
                    .addComponent(btn_tecla_r)
                    .addComponent(btn_tecla_t)
                    .addComponent(btn_tecla_y)
                    .addComponent(btn_tecla_u)
                    .addComponent(btn_tecla_i)
                    .addComponent(btn_tecla_o)
                    .addComponent(btn_tecla_p))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tecla_a)
                    .addComponent(btn_tecla_s)
                    .addComponent(btn_tecla_d)
                    .addComponent(btn_tecla_f)
                    .addComponent(btn_tecla_g)
                    .addComponent(btn_tecla_h)
                    .addComponent(btn_tecla_j)
                    .addComponent(btn_tecla_k)
                    .addComponent(btn_tecla_l)
                    .addComponent(lbl_smile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tecla_z)
                    .addComponent(btn_tecla_x)
                    .addComponent(btn_tecla_c)
                    .addComponent(btn_tecla_v)
                    .addComponent(btn_tecla_b)
                    .addComponent(btn_tecla_n)
                    .addComponent(btn_tecla_m)
                    .addComponent(btn_tecla_espaco))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tecla_qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_qActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_qActionPerformed

    private void btn_tecla_wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_wActionPerformed

    private void btn_tecla_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_eActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_eActionPerformed

    private void btn_tecla_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_rActionPerformed

    private void btn_tecla_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_tActionPerformed

    private void btn_tecla_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_yActionPerformed

    private void btn_tecla_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_uActionPerformed

    private void btn_tecla_iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_iActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_iActionPerformed

    private void btn_tecla_oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_oActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_oActionPerformed

    private void btn_tecla_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_pActionPerformed

    private void btn_tecla_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_gActionPerformed

    private void btn_tecla_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_hActionPerformed

    private void btn_tecla_jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_jActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_jActionPerformed

    private void btn_tecla_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_kActionPerformed

    private void btn_tecla_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_lActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_lActionPerformed

    private void btn_tecla_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_aActionPerformed

    private void btn_tecla_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_sActionPerformed

    private void btn_tecla_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_dActionPerformed

    private void btn_tecla_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_fActionPerformed

    private void btn_tecla_zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_zActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_zActionPerformed

    private void btn_tecla_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_xActionPerformed

    private void btn_tecla_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_cActionPerformed

    private void btn_tecla_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_vActionPerformed

    private void btn_tecla_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_bActionPerformed

    private void btn_tecla_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_nActionPerformed

    private void btn_tecla_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecla_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tecla_mActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teclado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tecla_a;
    private javax.swing.JButton btn_tecla_b;
    private javax.swing.JButton btn_tecla_c;
    private javax.swing.JButton btn_tecla_d;
    private javax.swing.JButton btn_tecla_e;
    private javax.swing.JButton btn_tecla_espaco;
    private javax.swing.JButton btn_tecla_f;
    private javax.swing.JButton btn_tecla_g;
    private javax.swing.JButton btn_tecla_h;
    private javax.swing.JButton btn_tecla_i;
    private javax.swing.JButton btn_tecla_j;
    private javax.swing.JButton btn_tecla_k;
    private javax.swing.JButton btn_tecla_l;
    private javax.swing.JButton btn_tecla_m;
    private javax.swing.JButton btn_tecla_n;
    private javax.swing.JButton btn_tecla_o;
    private javax.swing.JButton btn_tecla_p;
    private javax.swing.JButton btn_tecla_q;
    private javax.swing.JButton btn_tecla_r;
    private javax.swing.JButton btn_tecla_s;
    private javax.swing.JButton btn_tecla_t;
    private javax.swing.JButton btn_tecla_u;
    private javax.swing.JButton btn_tecla_v;
    private javax.swing.JButton btn_tecla_w;
    private javax.swing.JButton btn_tecla_x;
    private javax.swing.JButton btn_tecla_y;
    private javax.swing.JButton btn_tecla_z;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_mostrador;
    private javax.swing.JLabel lbl_smile;
    private javax.swing.JTextField txt_input;
    // End of variables declaration//GEN-END:variables
}
